### ISSUE TITLE
conferir parágrafo

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#19]
@suemi-higuchi veja a correção que fiz agora no arquivo f3f51273b46f19178c0ad82039c4dff2df1d4125

Vc pode depois conferir este parágrafo para tentarmos entender o que gerou este lixo que removi? Tenho receio de ter removido alguma informação relevante.

**Comment by arademaker** [comment]
Existem várias outras sentenças incompletas ou sem ponto final. Corrigi alguns casos em fb4244a3e usando o bom senso e tentando não perder dados mas tornando as sentenças completas.

Mas tem casos como https://github.com/cpdoc/dhbb/blob/master/text/1013.text#L40. 

@suemi-higuchi alguém para ajudar se eu gerar um relatório?

**Comment by arademaker** [comment]
casos de pontos faltantes: d3e4253fb, 4e91a43a6

**Comment by arademaker** [comment]
alguns casos de frases que terminam com `:` mas no parágrafo seguinte temos uma nova seção marcada em markdown com `##`

- [ ] https://github.com/cpdoc/dhbb/blob/master/text/6321.text#L672
- [ ] https://github.com/cpdoc/dhbb/blob/master/text/5802.text#L174
- [ ] https://github.com/cpdoc/dhbb/blob/master/text/8781.text#L66

**Comment by suemi-higuchi** [comment]
Revi/corrigi as questões q faltavam apontadas acima (b549ebf1d94d722fa51f1825e6c56455ac56ba29). Está aberto apenas o caso de `:` em https://github.com/cpdoc/dhbb/blob/master/text/6321.text#L672 pois se trata da ausência de algumas tabelas. A equipe está avaliando.

**Comment by arademaker** [comment]
Mais um caso:

2853.text linha 202  começa com:

>  'e9 de Magalhães Pinto e o senador Tancredo Neves. Com a incorporação do

**Comment by arademaker** [comment]
@suemi-higuchi vc poderia tentar me ajudar a fechar este e outros issues? @jaquepz ?

**Comment by suemi-higuchi** [comment]
Todos os verbetes mencionados neste issue foram revistos. Alguns já tinham sido corrigidos anteriormente e hoje fechamos o que faltava. Editamos bastante coisa do 4881 e alguns trechos do 6321 onde constavam tabelas no arquivo original.  @arademaker , quando vc der um merge do request que acabei de fazer, sinaliza o commit aqui.

**Comment by arademaker** [comment]
commit 9fc20446a4fb42c98d40d8f5d7038a24a1ba69a4 fecha este issue

**Comment by arademaker** [comment]
O arquivo 6321 tem alguns encodes estranhos:

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/86403/117561757-00223680-b070-11eb-8d2f-e8309fb663fc.png">


Estou corrigindo.
