### ISSUE TITLE
problemas nos arquivos: dados perdidos

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#20]
11270  linha 26 não parece ser fim de parágrafo, houve alguma perda de dados.

**Comment by arademaker** [comment]
primeiro parágrafo 4133 o ano de nascimento parece ter sido perdido.

**Comment by suemi-higuchi** [comment]
No caso do 4133, fui checar e encontrei duas versões DOC nas pastas do DHBB. Na mais antiga (2000), o texto está exatamente assim, com datas de nascimento e falecimento incompletas. E na versão mais recente (2008), sem a informação das datas. Como não existe estes dados nem na Internet, repliquei a versão 2008.

**Comment by suemi-higuchi** [comment]
No caso do 11270, fui checar no arquivo DOC original e consta exatamente assim. Vou encaminhar para a equipe resolver.

**Comment by suemi-higuchi** [comment]
> No caso do 11270, fui checar no arquivo DOC original e consta exatamente assim. Vou encaminhar para a equipe resolver.

Corrigido. Era mesmo fim de parágrafo. Ponto final ao invés de vírgula.

**Comment by arademaker** [comment]
Bom sempre citar o hash do commit

**Comment by arademaker** [comment]
O que falta para fechar este issue?

**Comment by suemi-higuchi** [comment]
> Bom sempre citar o hash do commit

Ah boa! Sempre esqueço.  Caso 11270:  dedafa706db21c575a924fa90f4038225a7de6d6 ; caso 4133: aa11ce3b2fabb3c0d89ecbb692adc6106f36d52a
