### ISSUE TITLE
frases incompletas

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#25]
https://github.com/cpdoc/dhbb/blob/master/text/11440.text#L35

@suemi-higuchi vc pode ajudar a verificar? Será que o texto for perdido na conversão?

**Comment by arademaker** [comment]
Outro caso:

https://github.com/cpdoc/dhbb/blob/master/text/12011.text#L80

**Comment by arademaker** [comment]
Outro caso:

https://github.com/cpdoc/dhbb/blob/master/text/1374.text#L52-L53

**Comment by suemi-higuchi** [comment]
@arademaker , não foi perdido na conversão não. Eu verifiquei os arquivos originais e vi que as frases incompletas são lapsos dos autores dos verbetes. Ajustei como pude e vou levar a questão para os coordenadores.

RODRIGUES, Carlos (Carlos Alberto Rodrigues Pinto)
- Excluí a frase 

ARAÚJO, Edinho (Edson Edinho Coelho Araújo)
- Excluí a frase, que me pareceu redundante com a próxima. 

COELHO, Fernando (Fernando de Vasconcelos Coelho)
- Substituí a vírgula pelo ponto final.

**Comment by arademaker** [comment]
Issue fechado no commit 824f464e1
