### ISSUE TITLE
comentário sobrando?

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#26]
https://github.com/cpdoc/dhbb/blob/master/text/11222.text#L74

Segmento entre parêntesis parece um comentário do editor que foi esquecido? @suemi-higuchi e @jaquepz?

**Comment by suemi-higuchi** [comment]
Sim, foi esquecido. Corrigido já!

**Comment by suemi-higuchi** [comment]
Corrigido no commit 77e4f225161bf78c6750c34f9ac4001d8a5e371d
