### ISSUE TITLE
dados incompletos

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#28]
Vide interrogaçõs em 

- https://github.com/cpdoc/dhbb/blob/master/text/11547.text#L12
- https://github.com/cpdoc/dhbb/blob/master/text/11547.text#L95 

Deixar documentos com estas interrogações faz parte dos procedimentos adotados no DHBB?

**Comment by suemi-higuchi** [comment]
Não, claro que não. Faltou revisão. Vamos resolver.

**Comment by suemi-higuchi** [comment]
Resolvido em b549ebf1d94d722fa51f1825e6c56455ac56ba29
