### ISSUE TITLE
meta comentários

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#29]
@suemi-higuchi , mais um comentário perdido no meio do texto:

https://github.com/cpdoc/dhbb/blob/master/text/1689.text#L110 (apenas remover?)

https://github.com/cpdoc/dhbb/blob/master/text/11174.text#L59. (seria o nome do editor? se sim, precisa ir para os metadados)

Pode corrigir?

**Comment by arademaker** [comment]
Em 89fac3252, segundo caso já corrigi.

**Comment by suemi-higuchi** [comment]
Corrigido e registrado para a equipe!
