### ISSUE TITLE
rever frase

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#30]
https://github.com/cpdoc/dhbb/blob/5a440d2ff5c4e82b565cff29cdd1d7c83aaf56c1/text/3783.text#L9-L12

talvez esteja certa, mas pode ficar mais clara talvez?

**Comment by vcvpaiva** [comment]
@arademaker a frase esta' correta e tradicional. que tal fechar o issue?

**Comment by suemi-higuchi** [comment]
Resolvido. Corrigimos a grafia do nome da biografada. https://github.com/cpdoc/dhbb/commit/eb304528c5011629a939d17e5d9fd3efebf24c79
