### ISSUE TITLE
corrigindo palavras

### ISSUE THREAD

**Issue by jaquepz** [cpdoc/dhbb#32]
Corrigindo erros ortográficos a partir de identificação automática no editor de texto (erros encontrados durante os exercícios da disciplina "Inteligência artificial aplicada às ciências humanas").

**Comment by arademaker** [comment]
dois ultimos commits resolvem este issue: https://github.com/cpdoc/dhbb/pull/34 e https://github.com/cpdoc/dhbb/pull/33. PR aceitos.
