### ISSUE TITLE
frase cortada?

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#38]
https://github.com/cpdoc/dhbb/blob/d2cd099379cba6f72acffd2429e3ff1ccf50f859/text/5222.text#L154-L168

**Comment by wellington36** [comment]
Acredito que houve corte também restante da frase [aqui](http://www.fgv.br/cpdoc/acervo/dicionarios/verbete-biografico/eduardo-matarazzo-suplicy).

**Comment by arademaker** [comment]
@suemi-higuchi outro caso que poderíamos tentar resolver antes da release?

**Comment by suemi-higuchi** [comment]
Resolvido em https://github.com/cpdoc/dhbb/commit/eb304528c5011629a939d17e5d9fd3efebf24c79
