### ISSUE TITLE
frase confusa

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#39]
https://github.com/cpdoc/dhbb/blob/d2cd099379cba6f72acffd2429e3ff1ccf50f859/text/11227.text#L263-L265

**Comment by wellington36** [comment]
Acredito que a confusão seja pelo sobrenome peculiar (Mantega) que acredito de referir a:

"Guido Mantega (Gênova, 7 de abril de 1949) é um economista brasileiro nascido na Itália. Durante o período que o PT esteve no Governo Federal ocupou vários cargos. Foi Ministro do Planejamento, Presidente do BNDES e Ministro da Fazenda nos dois mandatos do Presidente Lula. No primeiro mandato da presidente Dilma Rousseff continuou no comando da Fazenda." ( [texto extraído da Wikipedia](https://pt.wikipedia.org/wiki/Guido_Mantega) )

**Comment by arademaker** [comment]
Não é isso, me refiro ao ponto depois da sigla do partido seguido do verbo `gerou` em minúsculas. Neste caso, parece ter havido algum corte. O gerou não parece iniciar outra sentença e também seria estranho trocar o ponto pela virgula.

**Comment by vcvpaiva** [comment]
hmm, ja' que esta' investigando: e' interessante verificar porque nao tem a data do final do mandato. 
>---
title: MANTEGA, Guido
natureza: biográfico
sexo: m
cargos: 
 - min. Planejamento, Orçamento e Gestão 2003-2004
 - pres. BNDES 2004-2006
 - min. Faz. 2006-  
---
a Wikipedia diz 2015, possivelmente depois que o DHBB foi lancado. acho que tem que falar isso em algum lugar ou completar, nao?

**Comment by arademaker** [comment]
Sim, o time do CPDOC está se organizando para estas atualizações. @suemi-higuchi ? @jaquepz ?

**Comment by jaquepz** [comment]
Sim, o Guido faz parte do passivo a atualizar e, no momento, não temos time para atualizar esses verbetes. Concentramos os nossos esforços em verbetar os políticos ainda não verbetados pelo DHBB.

**Comment by suemi-higuchi** [comment]
Resolvido. Verbete atualizado. https://github.com/cpdoc/dhbb/commit/eb304528c5011629a939d17e5d9fd3efebf24c79
