### ISSUE TITLE
frase incompleta

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#42]
https://github.com/cpdoc/dhbb/blob/bea5dfcf12715a966275db28bc14925cbb81eb66/text/6089.text#L12-L13

**Comment by arademaker** [comment]
Ola @suemi-higuchi , acha que conseguimos fechar este issue antes da release?

**Comment by suemi-higuchi** [comment]
Resolvido em https://github.com/cpdoc/dhbb/commit/eb304528c5011629a939d17e5d9fd3efebf24c79
