### ISSUE TITLE
possíveis erros ortográficos

### ISSUE THREAD

**Issue by wellington36** [cpdoc/dhbb#48]
- freqüentou (doc 4121) (trema)
- co-autoria (docs 10921 e 11539) ([prefixo co-](http://www3.uol.com.br/qualidadeconteudo/portugues/prefixo-co--justapoe-se-a-todos-os-termos-exceto-os-iniciados-por-h.jhtm))
- co-autor (doc 11201) ([prefixo co-](http://www3.uol.com.br/qualidadeconteudo/portugues/prefixo-co--justapoe-se-a-todos-os-termos-exceto-os-iniciados-por-h.jhtm))

**Comment by wellington36** [comment]
Dos casos citados olhando para todos os textos do dhbb temos:

- 982 vezes "conseqüente"
- 736 vezes "conseqüência"
- 211 vezes "conseqüências"
- 153 vezes "freqüentou"
- 107 vezes "conseqüentemente"
- 105 vezes "freqüentes"
- 100 vezes "freqüência"
- (dentre outras 145 palavras com trema)

- 88 vezes "co-autoria"
- 26 vezes "co-autor"
- 8 vezes "co-gestão"
- (dentre outros 44 palavras)

**Comment by arademaker** [comment]
Em 8abab335b4f5e16567aa3b94fc0be32eb4fef918 corrigi os casos acima destacados pelo @wellington36. Existem outros casos de erros de grafia e o script `issue-48.sh` definitivamente não é a melhor forma de corrigir em batch erros ortográficos. 

1. palavras devem ser corrigidas, não sequencias de caracteres que podem ser parte de um palavra.
2. case-insensitive 
3. inflexões

Idealmente, uma correção em batch deveria considerar estes casos. Mas vou fechar o issue. considerando que a manutenção dos textos será sempre uma tarefa constante.

**Comment by arademaker** [comment]
Rodando 

```
% for f in *.text ; do cat $f | aspell --lang=pt_BR list ; done > miss
% sort miss | uniq -c | sort -nr   | wc -l
   28242
```

Ou seja, temos um total de 28K palavras não reconhecidas pelo aspell.  Muitas abreviações ou siglas. Casos óbvious acima de 100 ocorrências foram corrigidos em 475ddf89b.
