### ISSUE TITLE
DECRETO CAFÉ FILHO (Educação)

### ISSUE THREAD

**Issue by vcvpaiva** [cpdoc/dhbb#51]
https://github.com/cpdoc/dhbb/blob/master/text/5828.text

erro de transcricao? 213= 2/3?
>O diretório, representando os estudantes de cada instituto, seria
composto por, no máximo, nove membros eleitos por maioria absoluta, em
reunião a que estivessem presentes pelo menos 213 dos alunos
regularmente matriculados.

**Comment by suemi-higuchi** [comment]
Tem razão, Valéria, foi erro de digitação do autor. Estará corrigido no próximo commit! Muito obrigada!

**Comment by suemi-higuchi** [comment]
Corrigido em [2e153c9](https://github.com/cpdoc/dhbb/commit/2e153c9f6ca66e270baad78a164eabc19fad1b2e). Obrigada @vcvpaiva !
