### ISSUE TITLE
dados tabulares

### ISSUE THREAD

**Issue by lucasmation** [cpdoc/dhbb#54]
Parabéns pelo projeto! Voces tem os dados em versao tabular? Estou pensando em um CSV com colunas como: nome, dt_nascimento, municipio_nascimento (nome do municipio), etc...

**Comment by arademaker** [comment]
Não temos. O Objetivo do repositório é apenas divulgar os textos do DHBB, com o correto versionamento dos dados. Note que cada verbete é um arquivo YAML onde o primeiro documento contém os metadados. Não seria complicado escrever um parser em Python para ler os metadados e tabular como você preferir.  Mas os dados mencionados por você acima não estão geralmente nos metadados, devem ser extraídos dos parágrafos usando alguma técnica de NLP. Atualmente, muitas destas tarefas podem ser feitas, com os devidos cuidados, com os LLMs. Mesmo ChatGPT pode fazer um bom trabalho:

<img width="832" alt="image" src="https://github.com/user-attachments/assets/d3f0bed9-90e0-4464-9be4-5b4e214e8d1d">

**Comment by arademaker** [comment]
Outros serviços podem realizar a tarefa de forma semelhante e você também pode usar APIs para usar os modelos diretamente automatizando o processo para todos os arquivos. Veja resultado abaixo do https://www.ibm.com/products/watsonx-ai

<img width="832" alt="image" src="https://github.com/user-attachments/assets/8c0607e0-dce3-4518-a323-ea412d94a11b">

**Comment by lucasmation** [comment]
Certo. Muito obrigado!

**Comment by vcvpaiva** [comment]
Bom, o problema de usar LLMs pra fazer esse tipo de extracao e' que voce nao tem como medir os resultados. vc nao tem golden datasets e diferentes runs vao produzir resultados diferentes. o que voce inspeciona manualmente voce garante, mas e o resto?

**Comment by arademaker** [comment]
Bom, mesmo que tivéssemos um golden de um subconjunto dos dados, nenhuma garantia poderia ser dada além de algum expectativa de taxa de erro.

**Comment by vcvpaiva** [comment]
alguma expectativa de taxa de erro e' sempre melhor do que nenhuma medida.
