### ISSUE TITLE
Corpus Pedia

### ISSUE THREAD

**Issue by arademaker** [cpdoc/dhbb#9]
http://gramatica.usc.es/pln/resources/CorpusPedia.html wikipedia so' em portugues texto puro, deve dar pra fazer coisa a beca sobre o DHBB..

**Comment by vcvpaiva** [comment]
@arademaker outra possibilidade 'e usar a versao da BabelNet em portugues como uma versao estendida de OWN-PT-NEs, veja o codigo em https://github.com/nlpub/babelnet-extract.
(eu continuo dando sugestoes como a acima...)
